version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql5
    networks:
      - laravel
  
  mysql5:
    image: mysql:5.7.22
    container_name: mysql5
    restart: unless_stopped
    tty: true
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: laravel_vue_survey
      MYSQL_USER: root
      MYSQL_PASSWORD: abc123
      MYSQL_ROOT_PASSWORD: abc123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
  
  php:
    build:
      contex: .
      dockerfile: Dockerfile
    container_name: php8
    volumes:
      - ./:var/www
    ports:
      - "9000:9000"
    networks:
      - laravel
